version: '3'
services:
  web:
    container_name: docker-vue
    image: docker-vue
    build:
      context: .
      dockerfile: .docker/node.development.dockerfile
    volumes:
      - .:/var/www/docker-vue
      - /var/www/docker-vue/node_modules
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - "8080:8080"